//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.04 at 02:47:47 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.akilesa_kata.com/HelloService")
package com.akilesa_kata.helloservice;
